### ISSUE TITLE
In edit mode - selecting pulls can be difficult

### ISSUE THREAD

**Issue by Wotuu** [Wotuu/keystone.guru#707] opened 2021-03-09 20:52 UTC
I got mentioned by Kognos that this is an issue. He sent me a video detailing the issue, he uses the sidebar to switch pulls but it visibly does not want to cooperate about 50% of the time.

**Comment by merriry** [comment] 2021-03-19 16:36
to provide some more information on this issue, I have run into it a lot myself since I started using the site. It seems to only happen on my mac, and when I "click" a pull you very briefly (a few frames) get the animation for dragging a pull to change pull order. If, on my Mac I click as fast as I can, it will switch pulls properly. I tried covering the sensor with some opaque tape to see if it was related to movement, but it doesn't seem to be. I would describe it as going into click and hold mode MUCH too quickly. I am not a dev, so I am not sure where or what to look at in the code.

**Comment by Wotuu** [comment] 2021-03-20 17:30
Thanks for the additional info. I didn't look into this further but perhaps the library that I use for the drag and drop has some options to prevent this sort of behaviour. I'll try to see if I have some time tonight to look into this again.

**Comment by Wotuu** [comment] 2021-04-03 20:44
I just took a look at it (sorry it took so long) and I believe I have fixed it. Is currently available in the redesign site. I will very soon allow everyone to opt-in on the redesign.

**Comment by merriry** [comment] 2021-04-03 20:56
What ended up being the issue?

**Comment by Wotuu** [comment] 2021-04-06 08:13
So it was quite simple, I don't know why but Firefox required a delay between clicking and the actual drag action for it to work properly. So if you look very closely if you try to drag right now there will be a 100ms delay in being able to drag the pull. You will not really notice this as you use the feature, but it prevents the issue where just one click and it will think you're dragging it. Chrome didn't have this issue.

This commit eventually resolved it. https://github.com/Wotuu/keystone.guru/commit/e9d23d121172038f716cc7a8358aa0e079d82311

**Comment by Wotuu** [comment] 2021-11-02 10:09
Issue seems to be back when pressing the buttons in Firefox - Chrome is ok: https://discord.com/channels/482454450754289675/482822434106638346/904946804842446869

**Comment by Wotuu** [comment] 2022-04-30 15:08
Bump

**Comment by omicron-o** [comment] 2022-12-26 15:48
The issue is also resolved in firefox now. You can close this I think.

**Closed** 2023-02-18 13:44 UTC
Labels: bug
